/*
Developed by the European Commission - Directorate General for Maritime Affairs and Fisheries © European Union, 2015-2016.

This file is part of the Integrated Fisheries Data Management (IFDM) Suite. The IFDM Suite is free software: you can redistribute it 
and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of 
the License, or any later version. The IFDM Suite is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more 
details. You should have received a copy of the GNU General Public License along with the IFDM Suite. If not, see <http://www.gnu.org/licenses/>.

 */
package com.test;
// Generated Jul 28, 2015 2:11:57 PM by Hibernate Tools 4.3.1



/**
 * AllAreaV generated by hbm2java
 */
public class AllAreaV  implements java.io.Serializable {


     private Integer ?column?;

    public AllAreaV() {
    }

    public AllAreaV(Integer ?column?) {
       this.?column? = ?column?;
    }
   
    public Integer get?column?() {
        return this.?column?;
    }
    
    public void set?column?(Integer ?column?) {
        this.?column? = ?column?;
    }




}