package com.test;
// Generated Jul 28, 2015 2:11:57 PM by Hibernate Tools 4.3.1



/**
 * AllAreaV generated by hbm2java
 */
public class AllAreaV  implements java.io.Serializable {


     private Integer ?column?;

    public AllAreaV() {
    }

    public AllAreaV(Integer ?column?) {
       this.?column? = ?column?;
    }
   
    public Integer get?column?() {
        return this.?column?;
    }
    
    public void set?column?(Integer ?column?) {
        this.?column? = ?column?;
    }




}


