/*
Developed by the European Commission - Directorate General for Maritime Affairs and Fisheries © European Union, 2015-2016.

This file is part of the Integrated Fisheries Data Management (IFDM) Suite. The IFDM Suite is free software: you can redistribute it 
and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of 
the License, or any later version. The IFDM Suite is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more 
details. You should have received a copy of the GNU General Public License along with the IFDM Suite. If not, see <http://www.gnu.org/licenses/>.

 */
package com.test;

// Generated Jul 28, 2015 2:11:57 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * AreaGroup generated by hbm2java
 */
public class AreaGroup implements java.io.Serializable {

	private int id;
	private String name;
	private String groupDesc;
	private Set<AreaGroupMapping> areaGroupMappings = new HashSet<AreaGroupMapping>(
			0);

	public AreaGroup() {
	}

	public AreaGroup(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public AreaGroup(int id, String name, String groupDesc,
			Set<AreaGroupMapping> areaGroupMappings) {
		this.id = id;
		this.name = name;
		this.groupDesc = groupDesc;
		this.areaGroupMappings = areaGroupMappings;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getGroupDesc() {
		return this.groupDesc;
	}

	public void setGroupDesc(String groupDesc) {
		this.groupDesc = groupDesc;
	}

	public Set<AreaGroupMapping> getAreaGroupMappings() {
		return this.areaGroupMappings;
	}

	public void setAreaGroupMappings(Set<AreaGroupMapping> areaGroupMappings) {
		this.areaGroupMappings = areaGroupMappings;
	}

}