package com.test;

// Generated Jul 28, 2015 2:11:57 PM by Hibernate Tools 4.3.1

/**
 * AreaGroupMappingId generated by hbm2java
 */
public class AreaGroupMappingId implements java.io.Serializable {

	private long areaId;
	private int areaTypeId;
	private int areaGroupId;

	public AreaGroupMappingId() {
	}

	public AreaGroupMappingId(long areaId, int areaTypeId, int areaGroupId) {
		this.areaId = areaId;
		this.areaTypeId = areaTypeId;
		this.areaGroupId = areaGroupId;
	}

	public long getAreaId() {
		return this.areaId;
	}

	public void setAreaId(long areaId) {
		this.areaId = areaId;
	}

	public int getAreaTypeId() {
		return this.areaTypeId;
	}

	public void setAreaTypeId(int areaTypeId) {
		this.areaTypeId = areaTypeId;
	}

	public int getAreaGroupId() {
		return this.areaGroupId;
	}

	public void setAreaGroupId(int areaGroupId) {
		this.areaGroupId = areaGroupId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AreaGroupMappingId))
			return false;
		AreaGroupMappingId castOther = (AreaGroupMappingId) other;

		return (this.getAreaId() == castOther.getAreaId())
				&& (this.getAreaTypeId() == castOther.getAreaTypeId())
				&& (this.getAreaGroupId() == castOther.getAreaGroupId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getAreaId();
		result = 37 * result + this.getAreaTypeId();
		result = 37 * result + this.getAreaGroupId();
		return result;
	}

}
