/*
Developed by the European Commission - Directorate General for Maritime Affairs and Fisheries © European Union, 2015-2016.

This file is part of the Integrated Fisheries Data Management (IFDM) Suite. The IFDM Suite is free software: you can redistribute it 
and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of 
the License, or any later version. The IFDM Suite is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more 
details. You should have received a copy of the GNU General Public License along with the IFDM Suite. If not, see <http://www.gnu.org/licenses/>.

 */
package com.test;

// Generated Jul 28, 2015 2:11:57 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * AreaStatus generated by hbm2java
 */
public class AreaStatus implements java.io.Serializable {

	private long id;
	private UserAreas userAreas;
	private Date startDate;
	private Date endDate;
	private boolean isVisible;

	public AreaStatus() {
	}

	public AreaStatus(long id, UserAreas userAreas, Date startDate,
			Date endDate, boolean isVisible) {
		this.id = id;
		this.userAreas = userAreas;
		this.startDate = startDate;
		this.endDate = endDate;
		this.isVisible = isVisible;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public UserAreas getUserAreas() {
		return this.userAreas;
	}

	public void setUserAreas(UserAreas userAreas) {
		this.userAreas = userAreas;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public boolean isIsVisible() {
		return this.isVisible;
	}

	public void setIsVisible(boolean isVisible) {
		this.isVisible = isVisible;
	}

}