package com.test;

// Generated Jul 28, 2015 2:11:57 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * AreaStatus generated by hbm2java
 */
public class AreaStatus implements java.io.Serializable {

	private long id;
	private UserAreas userAreas;
	private Date startDate;
	private Date endDate;
	private boolean isVisible;

	public AreaStatus() {
	}

	public AreaStatus(long id, UserAreas userAreas, Date startDate,
			Date endDate, boolean isVisible) {
		this.id = id;
		this.userAreas = userAreas;
		this.startDate = startDate;
		this.endDate = endDate;
		this.isVisible = isVisible;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public UserAreas getUserAreas() {
		return this.userAreas;
	}

	public void setUserAreas(UserAreas userAreas) {
		this.userAreas = userAreas;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public boolean isIsVisible() {
		return this.isVisible;
	}

	public void setIsVisible(boolean isVisible) {
		this.isVisible = isVisible;
	}

}
