package com.test;

// Generated Jul 28, 2015 2:11:57 PM by Hibernate Tools 4.3.1

/**
 * AreaGroupMapping generated by hbm2java
 */
public class AreaGroupMapping implements java.io.Serializable {

	private AreaGroupMappingId id;
	private AreaGroup areaGroup;
	private AreaTypes areaTypes;

	public AreaGroupMapping() {
	}

	public AreaGroupMapping(AreaGroupMappingId id, AreaGroup areaGroup,
			AreaTypes areaTypes) {
		this.id = id;
		this.areaGroup = areaGroup;
		this.areaTypes = areaTypes;
	}

	public AreaGroupMappingId getId() {
		return this.id;
	}

	public void setId(AreaGroupMappingId id) {
		this.id = id;
	}

	public AreaGroup getAreaGroup() {
		return this.areaGroup;
	}

	public void setAreaGroup(AreaGroup areaGroup) {
		this.areaGroup = areaGroup;
	}

	public AreaTypes getAreaTypes() {
		return this.areaTypes;
	}

	public void setAreaTypes(AreaTypes areaTypes) {
		this.areaTypes = areaTypes;
	}

}
