/*
Developed by the European Commission - Directorate General for Maritime Affairs and Fisheries © European Union, 2015-2016.

This file is part of the Integrated Fisheries Data Management (IFDM) Suite. The IFDM Suite is free software: you can redistribute it 
and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of 
the License, or any later version. The IFDM Suite is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more 
details. You should have received a copy of the GNU General Public License along with the IFDM Suite. If not, see <http://www.gnu.org/licenses/>.

 */
package com.test;

// Generated Jul 28, 2015 2:11:57 PM by Hibernate Tools 4.3.1

/**
 * AreaGroupMapping generated by hbm2java
 */
public class AreaGroupMapping implements java.io.Serializable {

	private AreaGroupMappingId id;
	private AreaGroup areaGroup;
	private AreaTypes areaTypes;

	public AreaGroupMapping() {
	}

	public AreaGroupMapping(AreaGroupMappingId id, AreaGroup areaGroup,
			AreaTypes areaTypes) {
		this.id = id;
		this.areaGroup = areaGroup;
		this.areaTypes = areaTypes;
	}

	public AreaGroupMappingId getId() {
		return this.id;
	}

	public void setId(AreaGroupMappingId id) {
		this.id = id;
	}

	public AreaGroup getAreaGroup() {
		return this.areaGroup;
	}

	public void setAreaGroup(AreaGroup areaGroup) {
		this.areaGroup = areaGroup;
	}

	public AreaTypes getAreaTypes() {
		return this.areaTypes;
	}

	public void setAreaTypes(AreaTypes areaTypes) {
		this.areaTypes = areaTypes;
	}

}