/*
Developed by the European Commission - Directorate General for Maritime Affairs and Fisheries © European Union, 2015-2016.

This file is part of the Integrated Fisheries Data Management (IFDM) Suite. The IFDM Suite is free software: you can redistribute it 
and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of 
the License, or any later version. The IFDM Suite is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more 
details. You should have received a copy of the GNU General Public License along with the IFDM Suite. If not, see <http://www.gnu.org/licenses/>.

 */
package com.test;

// Generated Jul 28, 2015 2:11:57 PM by Hibernate Tools 4.3.1

/**
 * AreaGroupMappingId generated by hbm2java
 */
public class AreaGroupMappingId implements java.io.Serializable {

	private long areaId;
	private int areaTypeId;
	private int areaGroupId;

	public AreaGroupMappingId() {
	}

	public AreaGroupMappingId(long areaId, int areaTypeId, int areaGroupId) {
		this.areaId = areaId;
		this.areaTypeId = areaTypeId;
		this.areaGroupId = areaGroupId;
	}

	public long getAreaId() {
		return this.areaId;
	}

	public void setAreaId(long areaId) {
		this.areaId = areaId;
	}

	public int getAreaTypeId() {
		return this.areaTypeId;
	}

	public void setAreaTypeId(int areaTypeId) {
		this.areaTypeId = areaTypeId;
	}

	public int getAreaGroupId() {
		return this.areaGroupId;
	}

	public void setAreaGroupId(int areaGroupId) {
		this.areaGroupId = areaGroupId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AreaGroupMappingId))
			return false;
		AreaGroupMappingId castOther = (AreaGroupMappingId) other;

		return (this.getAreaId() == castOther.getAreaId())
				&& (this.getAreaTypeId() == castOther.getAreaTypeId())
				&& (this.getAreaGroupId() == castOther.getAreaGroupId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getAreaId();
		result = 37 * result + this.getAreaTypeId();
		result = 37 * result + this.getAreaGroupId();
		return result;
	}

}