/*
Developed by the European Commission - Directorate General for Maritime Affairs and Fisheries © European Union, 2015-2016.

This file is part of the Integrated Fisheries Data Management (IFDM) Suite. The IFDM Suite is free software: you can redistribute it 
and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of 
the License, or any later version. The IFDM Suite is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more 
details. You should have received a copy of the GNU General Public License along with the IFDM Suite. If not, see <http://www.gnu.org/licenses/>.

 */
package com.test;

// Generated Jul 28, 2015 2:11:57 PM by Hibernate Tools 4.3.1

/**
 * BookmarkId generated by hbm2java
 */
public class BookmarkId implements java.io.Serializable {

	private Integer srsCode;
	private String name;
	private String extent;

	public BookmarkId() {
	}

	public BookmarkId(Integer srsCode, String name, String extent) {
		this.srsCode = srsCode;
		this.name = name;
		this.extent = extent;
	}

	public Integer getSrsCode() {
		return this.srsCode;
	}

	public void setSrsCode(Integer srsCode) {
		this.srsCode = srsCode;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getExtent() {
		return this.extent;
	}

	public void setExtent(String extent) {
		this.extent = extent;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BookmarkId))
			return false;
		BookmarkId castOther = (BookmarkId) other;

		return ((this.getSrsCode() == castOther.getSrsCode()) || (this
				.getSrsCode() != null && castOther.getSrsCode() != null && this
				.getSrsCode().equals(castOther.getSrsCode())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null
						&& castOther.getName() != null && this.getName()
						.equals(castOther.getName())))
				&& ((this.getExtent() == castOther.getExtent()) || (this
						.getExtent() != null && castOther.getExtent() != null && this
						.getExtent().equals(castOther.getExtent())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getSrsCode() == null ? 0 : this.getSrsCode().hashCode());
		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result
				+ (getExtent() == null ? 0 : this.getExtent().hashCode());
		return result;
	}

}