package com.test;

// Generated Jul 28, 2015 2:11:57 PM by Hibernate Tools 4.3.1

/**
 * Bookmark generated by hbm2java
 */
public class Bookmark implements java.io.Serializable {

	private BookmarkId id;

	public Bookmark() {
	}

	public Bookmark(BookmarkId id) {
		this.id = id;
	}

	public BookmarkId getId() {
		return this.id;
	}

	public void setId(BookmarkId id) {
		this.id = id;
	}

}
