package com.test;

// Generated Jul 28, 2015 2:11:57 PM by Hibernate Tools 4.3.1

/**
 * Databasechangelog generated by hbm2java
 */
public class Databasechangelog implements java.io.Serializable {

	private DatabasechangelogId id;

	public Databasechangelog() {
	}

	public Databasechangelog(DatabasechangelogId id) {
		this.id = id;
	}

	public DatabasechangelogId getId() {
		return this.id;
	}

	public void setId(DatabasechangelogId id) {
		this.id = id;
	}

}
