/*
Developed by the European Commission - Directorate General for Maritime Affairs and Fisheries © European Union, 2015-2016.

This file is part of the Integrated Fisheries Data Management (IFDM) Suite. The IFDM Suite is free software: you can redistribute it 
and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of 
the License, or any later version. The IFDM Suite is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more 
details. You should have received a copy of the GNU General Public License along with the IFDM Suite. If not, see <http://www.gnu.org/licenses/>.

 */
package com.test;

// Generated Jul 28, 2015 2:11:57 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Databasechangeloglock generated by hbm2java
 */
public class Databasechangeloglock implements java.io.Serializable {

	private int id;
	private boolean locked;
	private Date lockgranted;
	private String lockedby;

	public Databasechangeloglock() {
	}

	public Databasechangeloglock(int id, boolean locked) {
		this.id = id;
		this.locked = locked;
	}

	public Databasechangeloglock(int id, boolean locked, Date lockgranted,
			String lockedby) {
		this.id = id;
		this.locked = locked;
		this.lockgranted = lockgranted;
		this.lockedby = lockedby;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public boolean isLocked() {
		return this.locked;
	}

	public void setLocked(boolean locked) {
		this.locked = locked;
	}

	public Date getLockgranted() {
		return this.lockgranted;
	}

	public void setLockgranted(Date lockgranted) {
		this.lockgranted = lockgranted;
	}

	public String getLockedby() {
		return this.lockedby;
	}

	public void setLockedby(String lockedby) {
		this.lockedby = lockedby;
	}

}