package com.test;

// Generated Jul 28, 2015 2:11:57 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Eez generated by hbm2java
 */
public class Eez implements java.io.Serializable {

	private int gid;
	private Serializable geom;
	private String eez;
	private String country;
	private String sovereign;
	private String remarks;
	private Integer sovId;
	private Integer eezId;
	private String iso3digit;
	private BigDecimal mrgid;
	private String dateChang;
	private Double areaM2;
	private Double longitude;
	private Double latitude;
	private Integer mrgidEez;

	public Eez() {
	}

	public Eez(int gid) {
		this.gid = gid;
	}

	public Eez(int gid, Serializable geom, String eez, String country,
			String sovereign, String remarks, Integer sovId, Integer eezId,
			String iso3digit, BigDecimal mrgid, String dateChang,
			Double areaM2, Double longitude, Double latitude, Integer mrgidEez) {
		this.gid = gid;
		this.geom = geom;
		this.eez = eez;
		this.country = country;
		this.sovereign = sovereign;
		this.remarks = remarks;
		this.sovId = sovId;
		this.eezId = eezId;
		this.iso3digit = iso3digit;
		this.mrgid = mrgid;
		this.dateChang = dateChang;
		this.areaM2 = areaM2;
		this.longitude = longitude;
		this.latitude = latitude;
		this.mrgidEez = mrgidEez;
	}

	public int getGid() {
		return this.gid;
	}

	public void setGid(int gid) {
		this.gid = gid;
	}

	public Serializable getGeom() {
		return this.geom;
	}

	public void setGeom(Serializable geom) {
		this.geom = geom;
	}

	public String getEez() {
		return this.eez;
	}

	public void setEez(String eez) {
		this.eez = eez;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getSovereign() {
		return this.sovereign;
	}

	public void setSovereign(String sovereign) {
		this.sovereign = sovereign;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public Integer getSovId() {
		return this.sovId;
	}

	public void setSovId(Integer sovId) {
		this.sovId = sovId;
	}

	public Integer getEezId() {
		return this.eezId;
	}

	public void setEezId(Integer eezId) {
		this.eezId = eezId;
	}

	public String getIso3digit() {
		return this.iso3digit;
	}

	public void setIso3digit(String iso3digit) {
		this.iso3digit = iso3digit;
	}

	public BigDecimal getMrgid() {
		return this.mrgid;
	}

	public void setMrgid(BigDecimal mrgid) {
		this.mrgid = mrgid;
	}

	public String getDateChang() {
		return this.dateChang;
	}

	public void setDateChang(String dateChang) {
		this.dateChang = dateChang;
	}

	public Double getAreaM2() {
		return this.areaM2;
	}

	public void setAreaM2(Double areaM2) {
		this.areaM2 = areaM2;
	}

	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	public Integer getMrgidEez() {
		return this.mrgidEez;
	}

	public void setMrgidEez(Integer mrgidEez) {
		this.mrgidEez = mrgidEez;
	}

}
