package com.test;

// Generated Jul 28, 2015 2:11:57 PM by Hibernate Tools 4.3.1

/**
 * Filter generated by hbm2java
 */
public class Filter implements java.io.Serializable {

	private FilterId id;
	private Report report;

	public Filter() {
	}

	public Filter(FilterId id, Report report) {
		this.id = id;
		this.report = report;
	}

	public FilterId getId() {
		return this.id;
	}

	public void setId(FilterId id) {
		this.id = id;
	}

	public Report getReport() {
		return this.report;
	}

	public void setReport(Report report) {
		this.report = report;
	}

}
