/*
Developed by the European Commission - Directorate General for Maritime Affairs and Fisheries © European Union, 2015-2016.

This file is part of the Integrated Fisheries Data Management (IFDM) Suite. The IFDM Suite is free software: you can redistribute it 
and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of 
the License, or any later version. The IFDM Suite is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more 
details. You should have received a copy of the GNU General Public License along with the IFDM Suite. If not, see <http://www.gnu.org/licenses/>.

 */
package com.test;

// Generated Jul 28, 2015 2:11:57 PM by Hibernate Tools 4.3.1

/**
 * FilterId generated by hbm2java
 */
public class FilterId implements java.io.Serializable {

	private String fltExpression;
	private long repId;
	private String dsScope;
	private String fltStyle;

	public FilterId() {
	}

	public FilterId(String fltExpression, long repId, String dsScope) {
		this.fltExpression = fltExpression;
		this.repId = repId;
		this.dsScope = dsScope;
	}

	public FilterId(String fltExpression, long repId, String dsScope,
			String fltStyle) {
		this.fltExpression = fltExpression;
		this.repId = repId;
		this.dsScope = dsScope;
		this.fltStyle = fltStyle;
	}

	public String getFltExpression() {
		return this.fltExpression;
	}

	public void setFltExpression(String fltExpression) {
		this.fltExpression = fltExpression;
	}

	public long getRepId() {
		return this.repId;
	}

	public void setRepId(long repId) {
		this.repId = repId;
	}

	public String getDsScope() {
		return this.dsScope;
	}

	public void setDsScope(String dsScope) {
		this.dsScope = dsScope;
	}

	public String getFltStyle() {
		return this.fltStyle;
	}

	public void setFltStyle(String fltStyle) {
		this.fltStyle = fltStyle;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FilterId))
			return false;
		FilterId castOther = (FilterId) other;

		return ((this.getFltExpression() == castOther.getFltExpression()) || (this
				.getFltExpression() != null
				&& castOther.getFltExpression() != null && this
				.getFltExpression().equals(castOther.getFltExpression())))
				&& (this.getRepId() == castOther.getRepId())
				&& ((this.getDsScope() == castOther.getDsScope()) || (this
						.getDsScope() != null && castOther.getDsScope() != null && this
						.getDsScope().equals(castOther.getDsScope())))
				&& ((this.getFltStyle() == castOther.getFltStyle()) || (this
						.getFltStyle() != null
						&& castOther.getFltStyle() != null && this
						.getFltStyle().equals(castOther.getFltStyle())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getFltExpression() == null ? 0 : this.getFltExpression()
						.hashCode());
		result = 37 * result + (int) this.getRepId();
		result = 37 * result
				+ (getDsScope() == null ? 0 : this.getDsScope().hashCode());
		result = 37 * result
				+ (getFltStyle() == null ? 0 : this.getFltStyle().hashCode());
		return result;
	}

}