package com.test;

// Generated Jul 28, 2015 2:11:57 PM by Hibernate Tools 4.3.1

/**
 * Gfcm generated by hbm2java
 */
public class Gfcm implements java.io.Serializable {

	private int id;

	public Gfcm() {
	}

	public Gfcm(int id) {
		this.id = id;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

}
