package com.test;

// Generated Jul 28, 2015 2:11:57 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Layer generated by hbm2java
 */
public class Layer implements java.io.Serializable {

	private int id;
	private boolean isBackground;
	private String name;
	private String layerDesc;
	private String serviceType;
	private String geoName;
	private Integer srsCode;
	private Set<ReportLayerMapping> reportLayerMappings = new HashSet<ReportLayerMapping>(
			0);

	public Layer() {
	}

	public Layer(int id, boolean isBackground, String name) {
		this.id = id;
		this.isBackground = isBackground;
		this.name = name;
	}

	public Layer(int id, boolean isBackground, String name, String layerDesc,
			String serviceType, String geoName, Integer srsCode,
			Set<ReportLayerMapping> reportLayerMappings) {
		this.id = id;
		this.isBackground = isBackground;
		this.name = name;
		this.layerDesc = layerDesc;
		this.serviceType = serviceType;
		this.geoName = geoName;
		this.srsCode = srsCode;
		this.reportLayerMappings = reportLayerMappings;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public boolean isIsBackground() {
		return this.isBackground;
	}

	public void setIsBackground(boolean isBackground) {
		this.isBackground = isBackground;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLayerDesc() {
		return this.layerDesc;
	}

	public void setLayerDesc(String layerDesc) {
		this.layerDesc = layerDesc;
	}

	public String getServiceType() {
		return this.serviceType;
	}

	public void setServiceType(String serviceType) {
		this.serviceType = serviceType;
	}

	public String getGeoName() {
		return this.geoName;
	}

	public void setGeoName(String geoName) {
		this.geoName = geoName;
	}

	public Integer getSrsCode() {
		return this.srsCode;
	}

	public void setSrsCode(Integer srsCode) {
		this.srsCode = srsCode;
	}

	public Set<ReportLayerMapping> getReportLayerMappings() {
		return this.reportLayerMappings;
	}

	public void setReportLayerMappings(
			Set<ReportLayerMapping> reportLayerMappings) {
		this.reportLayerMappings = reportLayerMappings;
	}

}
