package com.test;

// Generated Jul 28, 2015 2:11:57 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * LayerGroup generated by hbm2java
 */
public class LayerGroup implements java.io.Serializable {

	private long id;
	private Integer groupOrder;
	private String groupName;
	private Set<ReportLayerMapping> reportLayerMappings = new HashSet<ReportLayerMapping>(
			0);

	public LayerGroup() {
	}

	public LayerGroup(long id, String groupName) {
		this.id = id;
		this.groupName = groupName;
	}

	public LayerGroup(long id, Integer groupOrder, String groupName,
			Set<ReportLayerMapping> reportLayerMappings) {
		this.id = id;
		this.groupOrder = groupOrder;
		this.groupName = groupName;
		this.reportLayerMappings = reportLayerMappings;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Integer getGroupOrder() {
		return this.groupOrder;
	}

	public void setGroupOrder(Integer groupOrder) {
		this.groupOrder = groupOrder;
	}

	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public Set<ReportLayerMapping> getReportLayerMappings() {
		return this.reportLayerMappings;
	}

	public void setReportLayerMappings(
			Set<ReportLayerMapping> reportLayerMappings) {
		this.reportLayerMappings = reportLayerMappings;
	}

}
