package com.test;

// Generated Jul 28, 2015 2:11:57 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;

/**
 * ReportExecutionLog generated by hbm2java
 */
public class ReportExecutionLog implements java.io.Serializable {

	private long id;
	private Report report;
	private Serializable executedBy;
	private Date executedOn;

	public ReportExecutionLog() {
	}

	public ReportExecutionLog(long id, Report report, Serializable executedBy,
			Date executedOn) {
		this.id = id;
		this.report = report;
		this.executedBy = executedBy;
		this.executedOn = executedOn;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Report getReport() {
		return this.report;
	}

	public void setReport(Report report) {
		this.report = report;
	}

	public Serializable getExecutedBy() {
		return this.executedBy;
	}

	public void setExecutedBy(Serializable executedBy) {
		this.executedBy = executedBy;
	}

	public Date getExecutedOn() {
		return this.executedOn;
	}

	public void setExecutedOn(Date executedOn) {
		this.executedOn = executedOn;
	}

}
