package com.test;

// Generated Jul 28, 2015 2:11:57 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Report generated by hbm2java
 */
public class Report implements java.io.Serializable {

	private long id;
	private String name;
	private Date createdOn;
	private String description;
	private String createdBy;
	private Set<Filter> filters = new HashSet<Filter>(0);
	private Set<ReportLayerMapping> reportLayerMappings = new HashSet<ReportLayerMapping>(
			0);
	private Set<ReportExecutionLog> reportExecutionLogs = new HashSet<ReportExecutionLog>(
			0);

	public Report() {
	}

	public Report(long id, String name, Date createdOn, String createdBy) {
		this.id = id;
		this.name = name;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
	}

	public Report(long id, String name, Date createdOn, String description,
			String createdBy, Set<Filter> filters,
			Set<ReportLayerMapping> reportLayerMappings,
			Set<ReportExecutionLog> reportExecutionLogs) {
		this.id = id;
		this.name = name;
		this.createdOn = createdOn;
		this.description = description;
		this.createdBy = createdBy;
		this.filters = filters;
		this.reportLayerMappings = reportLayerMappings;
		this.reportExecutionLogs = reportExecutionLogs;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Set<Filter> getFilters() {
		return this.filters;
	}

	public void setFilters(Set<Filter> filters) {
		this.filters = filters;
	}

	public Set<ReportLayerMapping> getReportLayerMappings() {
		return this.reportLayerMappings;
	}

	public void setReportLayerMappings(
			Set<ReportLayerMapping> reportLayerMappings) {
		this.reportLayerMappings = reportLayerMappings;
	}

	public Set<ReportExecutionLog> getReportExecutionLogs() {
		return this.reportExecutionLogs;
	}

	public void setReportExecutionLogs(
			Set<ReportExecutionLog> reportExecutionLogs) {
		this.reportExecutionLogs = reportExecutionLogs;
	}

}
