/*
Developed by the European Commission - Directorate General for Maritime Affairs and Fisheries © European Union, 2015-2016.

This file is part of the Integrated Fisheries Data Management (IFDM) Suite. The IFDM Suite is free software: you can redistribute it 
and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of 
the License, or any later version. The IFDM Suite is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more 
details. You should have received a copy of the GNU General Public License along with the IFDM Suite. If not, see <http://www.gnu.org/licenses/>.

 */
package com.test;

// Generated Jul 28, 2015 2:11:57 PM by Hibernate Tools 4.3.1

/**
 * SpatialConfiguration generated by hbm2java
 */
public class SpatialConfiguration implements java.io.Serializable {

	private int id;
	private String propertyName;
	private String propValue;
	private String propValidator;
	private String comments;

	public SpatialConfiguration() {
	}

	public SpatialConfiguration(int id) {
		this.id = id;
	}

	public SpatialConfiguration(int id, String propertyName, String propValue,
			String propValidator, String comments) {
		this.id = id;
		this.propertyName = propertyName;
		this.propValue = propValue;
		this.propValidator = propValidator;
		this.comments = comments;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getPropertyName() {
		return this.propertyName;
	}

	public void setPropertyName(String propertyName) {
		this.propertyName = propertyName;
	}

	public String getPropValue() {
		return this.propValue;
	}

	public void setPropValue(String propValue) {
		this.propValue = propValue;
	}

	public String getPropValidator() {
		return this.propValidator;
	}

	public void setPropValidator(String propValidator) {
		this.propValidator = propValidator;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

}