/*
Developed by the European Commission - Directorate General for Maritime Affairs and Fisheries © European Union, 2015-2016.

This file is part of the Integrated Fisheries Data Management (IFDM) Suite. The IFDM Suite is free software: you can redistribute it 
and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of 
the License, or any later version. The IFDM Suite is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more 
details. You should have received a copy of the GNU General Public License along with the IFDM Suite. If not, see <http://www.gnu.org/licenses/>.

 */
package com.test;

// Generated Jul 28, 2015 2:11:57 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * UserAreas generated by hbm2java
 */
public class UserAreas implements java.io.Serializable {

	private long id;
	private String name;
	private String subtype;
	private String areaDesc;
	private Serializable geom;
	private Set<AreaStatus> areaStatuses = new HashSet<AreaStatus>(0);

	public UserAreas() {
	}

	public UserAreas(long id, String name, String subtype, Serializable geom) {
		this.id = id;
		this.name = name;
		this.subtype = subtype;
		this.geom = geom;
	}

	public UserAreas(long id, String name, String subtype, String areaDesc,
			Serializable geom, Set<AreaStatus> areaStatuses) {
		this.id = id;
		this.name = name;
		this.subtype = subtype;
		this.areaDesc = areaDesc;
		this.geom = geom;
		this.areaStatuses = areaStatuses;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSubtype() {
		return this.subtype;
	}

	public void setSubtype(String subtype) {
		this.subtype = subtype;
	}

	public String getAreaDesc() {
		return this.areaDesc;
	}

	public void setAreaDesc(String areaDesc) {
		this.areaDesc = areaDesc;
	}

	public Serializable getGeom() {
		return this.geom;
	}

	public void setGeom(Serializable geom) {
		this.geom = geom;
	}

	public Set<AreaStatus> getAreaStatuses() {
		return this.areaStatuses;
	}

	public void setAreaStatuses(Set<AreaStatus> areaStatuses) {
		this.areaStatuses = areaStatuses;
	}

}