package eu.europa.ec.fisheries.uvms.spatial.entity;

import lombok.EqualsAndHashCode;
import lombok.ToString;

import javax.persistence.*;
import java.io.Serializable;

/**
 * Generated by InteliJ Hibernate plugin on 04-Aug-15.
 */

@Entity
@Table(name = "area_types", schema = "spatial", catalog = "uvms")
@EqualsAndHashCode
@ToString
@NamedQueries({
        @NamedQuery(name = AreaTypeEntity.FIND_ALL, query = "SELECT a.typeName FROM AreaTypeEntity a"),
        @NamedQuery(name = AreaTypeEntity.FIND_SYSTEM, query = "SELECT a FROM AreaTypeEntity a"), //TODO add filtering by T/F 'system_area' column
})
public class AreaTypeEntity implements Serializable {

    private static final long serialVersionUID = 6236757220282097320L;

    public static final String FIND_ALL = "AreaType.findAll";
    public static final String FIND_SYSTEM = "AreaType.findSystem";

    private int id;
    private String typeName;
    private String areaTypeDesc;
    private String areaDbTable;
    private String geoName;
    private int srsCode;

    @Id
    @Column(name = "id")
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Basic
    @Column(name = "type_name")
    public String getTypeName() {
        return typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    @Basic
    @Column(name = "area_type_desc")
    public String getAreaTypeDesc() {
        return areaTypeDesc;
    }

    public void setAreaTypeDesc(String areaTypeDesc) {
        this.areaTypeDesc = areaTypeDesc;
    }

    @Basic
    @Column(name = "area_db_table")
    public String getAreaDbTable() {
        return areaDbTable;
    }

    public void setAreaDbTable(String areaDbTable) {
        this.areaDbTable = areaDbTable;
    }

    @Basic
    @Column(name = "geo_name")
    public String getGeoName() {
        return geoName;
    }

    public void setGeoName(String geoName) {
        this.geoName = geoName;
    }

    @Basic
    @Column(name = "srs_code")
    public int getSrsCode() {
        return srsCode;
    }

    public void setSrsCode(int srsCode) {
        this.srsCode = srsCode;
    }

}
