package eu.europa.ec.fisheries.uvms.spatial.entity;

import javax.persistence.*;

/**
 * Generated by InteliJ Hibernate plugin on 04-Aug-15.
 */

@Entity
@Table(name = "area_types", schema = "spatial", catalog = "uvms")
public class AreaTypeEntity { // TODO  please use lombok @Data like CountryEntity
    private int id;
    private String typeName;
    private String areaTypeDesc;
    private String areaDbTable;
    private String geoName;
    private int srsCode;

    @Id
    @Column(name = "id")
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Basic
    @Column(name = "type_name")
    public String getTypeName() {
        return typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    @Basic
    @Column(name = "area_type_desc")
    public String getAreaTypeDesc() {
        return areaTypeDesc;
    }

    public void setAreaTypeDesc(String areaTypeDesc) {
        this.areaTypeDesc = areaTypeDesc;
    }

    @Basic
    @Column(name = "area_db_table")
    public String getAreaDbTable() {
        return areaDbTable;
    }

    public void setAreaDbTable(String areaDbTable) {
        this.areaDbTable = areaDbTable;
    }

    @Basic
    @Column(name = "geo_name")
    public String getGeoName() {
        return geoName;
    }

    public void setGeoName(String geoName) {
        this.geoName = geoName;
    }

    @Basic
    @Column(name = "srs_code")
    public int getSrsCode() {
        return srsCode;
    }

    public void setSrsCode(int srsCode) {
        this.srsCode = srsCode;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        AreaTypeEntity areaTypeEntity = (AreaTypeEntity) o;

        if (id != areaTypeEntity.id) return false;
        if (srsCode != areaTypeEntity.srsCode) return false;
        if (typeName != null ? !typeName.equals(areaTypeEntity.typeName) : areaTypeEntity.typeName != null) return false;
        if (areaTypeDesc != null ? !areaTypeDesc.equals(areaTypeEntity.areaTypeDesc) : areaTypeEntity.areaTypeDesc != null) return false;
        if (areaDbTable != null ? !areaDbTable.equals(areaTypeEntity.areaDbTable) : areaTypeEntity.areaDbTable != null) return false;
        if (geoName != null ? !geoName.equals(areaTypeEntity.geoName) : areaTypeEntity.geoName != null) return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = id;
        result = 31 * result + (typeName != null ? typeName.hashCode() : 0);
        result = 31 * result + (areaTypeDesc != null ? areaTypeDesc.hashCode() : 0);
        result = 31 * result + (areaDbTable != null ? areaDbTable.hashCode() : 0);
        result = 31 * result + (geoName != null ? geoName.hashCode() : 0);
        result = 31 * result + srsCode;
        return result;
    }
}
